{
 "title": "Microservice dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "name", "query": "label_values(name)" },
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" },
   { "name": "metrictype", "label": "metrictype", "query": "label_values(metric_type)" },
   {
    "name": "interval",
    "label": "interval",
    "query": "15s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Counter rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "events/interval" }
   ],
   "targets": [
    {
     "expr": "rate(microservice_summaries_count{namespace=~\"$namespace\",name=~\"$name\",metric_type=~\"$metrictype\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "microservice_exceptions", "legendFormat": "{{exception_name}}" }
   ]
  },
  {
   "title": "Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(microservice_summaries_sum{namespace=~\"$namespace\",name=~\"$name\",metric_type=~\"$metrictype\"}[$interval])/rate(microservice_summaries_count{namespace=~\"$namespace\",name=~\"$name\",metric_type=~\"$metrictype\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}