# prometheus.yml
global:
    scrape_interval: 3s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      target_groups:
          - targets: ['localhost:9090']
    # - job_name: 'node-exporter'
    #   target_groups:
    #       - targets: ['node-exporter:9100']
    - job_name: 'pushgateway'
      honor_labels: true
      scrape_interval: 5s
      target_groups:
          - targets: ['host.docker.internal:9091']