name: CI

on:
  push:
    tags:
      - '*'
    branches-ignore:
      - '!release/**'
      
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
               
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Build
      run: dotnet build ConsoleApp1/ConsoleApp1.sln --configuration Release
