name: Continous Delivery

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          dotnet build ./src/Acnys/Acnys.sln --configuration Release -p:Version=$tag

      - name: Test
        run: dotnet test ./src/Acnys/Acnys.sln

      - name: Pack
        run: |
          dotnet pack ./src/Acnys/Acnys.sln --configuration Release -p:Version=$tag --output ./packages --include-symbols --include-source

      - name: publish
        run: dotnet nuget push ./packages/**/*.nupkg --skip-duplicate true --no-symbols true --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nuget_api_key }}
