name: Continous Delivery (master branch)

on:
  push:    
    branches:
      - master
      
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
               
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Build
      run: dotnet build ./src/Acnys/Acnys.sln --configuration Release
    
    - name: Test
      run: dotnet test ./src/Acnys/Acnys.sln
    
    - name: Pack
      run: |
        dotnet pack ./src/Acnys/Acnys.sln --configuration Release --output ./packages --include-symbols --include-source

    - name: publish      
      run: dotnet nuget push ./packages/**/*.nupkg --skip-duplicate true --no-symbols true --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nuget_api_key }}
